# .streamlit/secrets.toml
GOOGLE_API_KEY = "AIzaSyDtieut7Av7FW6PoMQvGA5m6x5MYVOOaow"
TAVILY_API_KEY = "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"
LINKEDIN_ACCESS_TOKEN = "AQVex2T7u7wEnZzsvxfYP3xivqTwqilrvyCUvCF__TcJ2IHr4Rtazr7zaLPekK5XBsXHwzoxdlIPr0Ljz4NR-pI-z7OEfFY6Ar5hwrEUhsjtz2IZwJAJpclzSvCFwYdPcEYFPGdvZ8zKdhseFsVXpR9ribEx6ls9KSlJ21fLFc1T97Ak9aQvB-Jxcv-VcrWDf7Ty_wmwu7lly-6TPA8MpMoNJU15nA-1CnbJPgr2Mj15ChOwB66h8q1nSdv68ZcDFld1ESSt9ldw-xG1ufdnN1p78cDMsF-QlSGUdgCYMQpt041xBqtYLvzwYWhdro1TY7usyWz0Hk654szP1vt-lH0hQWUsnA"
MY_GITHUB_URL="https://github.com/DataScienceVishal"
MY_LINKEDIN_URL="https://www.linkedin.com/in/vishalkhandatascience/"